<?php

namespace Database\Seeders;

use App\Models\Raca;
use Illuminate\Database\Seeder;

class RacasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $racas = '[
            {"tipo":1, "raca":"Sem Raça Definida"},
            {"tipo":1, "raca":"Labrador Retriever"},
            {"tipo":1, "raca":"Golden Retriever"},
            {"tipo":1, "raca":"Bulldog Francês"},
            {"tipo":1, "raca":"Poodle"},
            {"tipo":1, "raca":"Beagle"},
            {"tipo":1, "raca":"Boxer"},
            {"tipo":1, "raca":"Pastor Alemão"},
            {"tipo":1, "raca":"Yorkshire Terrier"},
            {"tipo":1, "raca":"Dachshund"},
            {"tipo":1, "raca":"Chihuahua"},
            {"tipo":1, "raca":"Shih Tzu"},
            {"tipo":1, "raca":"Rottweiler"},
            {"tipo":1, "raca":"Border Collie"},
            {"tipo":1, "raca":"Bichon Frisé"},
            {"tipo":1, "raca":"Pug"},
            {"tipo":1, "raca":"Schnauzer"},
            {"tipo":1, "raca":"Husky Siberiano"},
            {"tipo":1, "raca":"Dalmatian"},
            {"tipo":1, "raca":"Doberman"},
            {"tipo":1, "raca":"Maltese"},
            {"tipo":2, "raca":"Sem Raça Definida"},
            {"tipo":2, "raca":"Siamês"},
            {"tipo":2, "raca":"Persa"},
            {"tipo":2, "raca":"Bengal"},
            {"tipo":2, "raca":"Maine Coon"},
            {"tipo":2, "raca":"Sphynx"},
            {"tipo":2, "raca":"Ragdoll"},
            {"tipo":2, "raca":"British Shorthair"},
            {"tipo":2, "raca":"Scottish Fold"},
            {"tipo":2, "raca":"Burmese"},
            {"tipo":2, "raca":"Abissínio"},
            {"tipo":2, "raca":"Siberiano"},
            {"tipo":2, "raca":"Norueguês da Floresta"},
            {"tipo":2, "raca":"Birmanês"},
            {"tipo":2, "raca":"Burmês"},
            {"tipo":2, "raca":"Rex"},
            {"tipo":2, "raca":"Angorá"},
            {"tipo":2, "raca":"Himalaio"},
            {"tipo":2, "raca":"Tonquinês"},
            {"tipo":2, "raca":"Exótico"},
            {"tipo":3, "raca":"Sem Raça Definida"},
            {"tipo":3, "raca":"Coelho Angorá"},
            {"tipo":3, "raca":"Coelho Rex"},
            {"tipo":3, "raca":"Coelho Holandês"},
            {"tipo":3, "raca":"Coelho Mini Rex"},
            {"tipo":3, "raca":"Coelho Lion Head"},
            {"tipo":3, "raca":"Coelho Mini Lop"},
            {"tipo":3, "raca":"Coelho Dutch"},
            {"tipo":3, "raca":"Coelho Mini Lion Head"},
            {"tipo":3, "raca":"Coelho Hotot"},
            {"tipo":3, "raca":"Coelho Himalaio"},
            {"tipo":3, "raca":"Coelho Californiano"},
            {"tipo":3, "raca":"Coelho Polonês"},
            {"tipo":3, "raca":"Coelho Flemish Giant"},
            {"tipo":3, "raca":"Coelho Mini Plush Lop"},
            {"tipo":3, "raca":"Coelho Teddy Dwerg"},
            {"tipo":3, "raca":"Coelho Belier"},
            {"tipo":3, "raca":"Coelho Cashmere Lop"},
            {"tipo":3, "raca":"Coelho Harlequin"},
            {"tipo":3, "raca":"Coelho Silver Fox"},
            {"tipo":4,"raca":"Sem Raça Definida"},
            {"tipo":4,"raca":"Hamster Sírio"},
            {"tipo":4,"raca":"Hamster Roborovski"},
            {"tipo":4,"raca":"Hamster Anão Russo"},
            {"tipo":4,"raca":"Hamster Chinês"},
            {"tipo":4,"raca":"Hamster Anão de Campbell"},
            {"tipo":4,"raca":"Hamster Anão de Inverno"},
            {"tipo":4,"raca":"Hamster Anão de Dzungarian"},
            {"tipo":4,"raca":"Hamster Panda"},
            {"tipo":4,"raca":"Hamster Teddy Bear"},
            {"tipo":4,"raca":"Hamster Angorá"},
            {"tipo":4,"raca":"Hamster Dourado"},
            {"tipo":4,"raca":"Hamster Preto"},
            {"tipo":4,"raca":"Hamster Albino"},
            {"tipo":4,"raca":"Hamster Bico de Pato"},
            {"tipo":4,"raca":"Hamster Enchilada"},
            {"tipo":4,"raca":"Hamster Sirio de Pelo Longo"},
            {"tipo":4,"raca":"Hamster Cinza"},
            {"tipo":4,"raca":"Hamster Topolino"},
            {"tipo":4,"raca":"Hamster Grande Anão Russo"},
            {"tipo":5,"raca":"Sem Raça Definida"},
            {"tipo":5,"raca":"Quarto de Milha"},
            {"tipo":5,"raca":"Mangalarga Marchador"},
            {"tipo":5,"raca":"Puro Sangue Inglês (PSI)"},
            {"tipo":5,"raca":"Puro Sangue Árabe"},
            {"tipo":5,"raca":"Lusitano"},
            {"tipo":5,"raca":"Paint Horse"},
            {"tipo":5,"raca":"Appaloosa"},
            {"tipo":5,"raca":"Brasileiro de Hipismo (BH)"},
            {"tipo":5,"raca":"Campolina"},
            {"tipo":5,"raca":"Friesian"},
            {"tipo":5,"raca":"Cavalo Andaluz"},
            {"tipo":5,"raca":"Cavalo Bretão"},
            {"tipo":5,"raca":"Cavalo Percheron"},
            {"tipo":5,"raca":"Cavalo de Sela Francês"},
            {"tipo":5,"raca":"Cavalo de Sela Belga"},
            {"tipo":5,"raca":"Cavalo Haflinger"},
            {"tipo":5,"raca":"Cavalo Tennessee Walking"},
            {"tipo":5,"raca":"Cavalo Oldenburg"},
            {"tipo":5,"raca":"Cavalo Shire"},
            {"tipo":6,"raca":"Sem Raça Definida"},
            {"tipo":6,"raca":"Canário"},
            {"tipo":6,"raca":"Calopsita"},
            {"tipo":6,"raca":"Papagaio"},
            {"tipo":6,"raca":"Periquito Australiano"},
            {"tipo":6,"raca":"Agapornis"},
            {"tipo":6,"raca":"Cacatua"},
            {"tipo":6,"raca":"Galinha-da-Angola"},
            {"tipo":6,"raca":"Diamante-de-Gould"},
            {"tipo":6,"raca":"Rosela"},
            {"tipo":6,"raca":"Pintassilgo"},
            {"tipo":6,"raca":"Trinca-ferro"},
            {"tipo":6,"raca":"Canário Belga"},
            {"tipo":6,"raca":"Curió"},
            {"tipo":6,"raca":"Sabiá"},
            {"tipo":6,"raca":"Coleirinha"},
            {"tipo":6,"raca":"Saracura"},
            {"tipo":6,"raca":"Galo-de-campina"},
            {"tipo":6,"raca":"Sanhaço"},
            {"tipo":6,"raca":"Tico-tico"},
            {"tipo":7,"raca":"Sem Raça Definida"},
            {"tipo":7,"raca":"Betta"},
            {"tipo":7,"raca":"Guppy"},
            {"tipo":7,"raca":"Neon"},
            {"tipo":7,"raca":"Kinguio"},
            {"tipo":7,"raca":"Platy"},
            {"tipo":7,"raca":"Espada"},
            {"tipo":7,"raca":"Tetra"},
            {"tipo":7,"raca":"Acará"},
            {"tipo":7,"raca":"Disco"},
            {"tipo":7,"raca":"Barbo"},
            {"tipo":7,"raca":"Cascudo"},
            {"tipo":7,"raca":"Ciclídeo"},
            {"tipo":7,"raca":"Molinésia"},
            {"tipo":7,"raca":"Peixe-Anjo"},
            {"tipo":7,"raca":"Peixe-Cofre"},
            {"tipo":7,"raca":"Peixe-Borboleta"},
            {"tipo":7,"raca":"Carpa"},
            {"tipo":7,"raca":"Dourado"},
            {"tipo":7,"raca":"Mandarim"},
            {"tipo":8,"raca":"Sem Raça Definida"},
            {"tipo":8,"raca":"Tartaruga-de-orelha-vermelha"},
            {"tipo":8,"raca":"Tartaruga-de-orelha-amarela"},
            {"tipo":8,"raca":"Tartaruga-de-pente"},
            {"tipo":8,"raca":"Tartaruga-sulcata"},
            {"tipo":8,"raca":"Tartaruga-mordedora"},
            {"tipo":8,"raca":"Tartaruga-de-água-europeia"},
            {"tipo":8,"raca":"Tartaruga-leopardo"},
            {"tipo":8,"raca":"Tartaruga-pintada"},
            {"tipo":8,"raca":"Tartaruga-de-esporas"},
            {"tipo":8,"raca":"Tartaruga-de-pescoço-longo"},
            {"tipo":8,"raca":"Tartaruga-mosquito"},
            {"tipo":8,"raca":"Tartaruga-oliva"},
            {"tipo":8,"raca":"Tartaruga-grega"},
            {"tipo":8,"raca":"Tartaruga-verde"},
            {"tipo":8,"raca":"Tartaruga-casco-mole"},
            {"tipo":8,"raca":"Tartaruga-australiana"},
            {"tipo":8,"raca":"Tartaruga-das-galápagos"},
            {"tipo":8,"raca":"Tartaruga-marinha"},
            {"tipo":8,"raca":"Tartaruga-de-couro"},
            {"tipo":9,"raca":"Sem Raça Definida"},
            {"tipo":9,"raca":"Python-real"},
            {"tipo":9,"raca":"Corn Snake"},
            {"tipo":9,"raca":"Cobra-de-Escada"},
            {"tipo":9,"raca":"Cobra-Coral"},
            {"tipo":9,"raca":"Pit Viper"},
            {"tipo":9,"raca":"King Snake"},
            {"tipo":9,"raca":"Anaconda"},
            {"tipo":9,"raca":"Cobra-Cega"},
            {"tipo":9,"raca":"Cobra-Rei"},
            {"tipo":9,"raca":"Cobra-Capelo"},
            {"tipo":9,"raca":"Cobra-Naja"},
            {"tipo":9,"raca":"Cobra-Rato"},
            {"tipo":9,"raca":"Cobra-de-vidro"},
            {"tipo":9,"raca":"Cobra-da-água"},
            {"tipo":9,"raca":"Cobra-Preta"},
            {"tipo":9,"raca":"Cobra-da-água-japonesa"},
            {"tipo":9,"raca":"Cobra-das-Mangues"},
            {"tipo":9,"raca":"Cobra-Marrom"},
            {"tipo":9,"raca":"Cobra-tigre"},
            {"tipo":10,"raca":"Sem Raça Definida"},
            {"tipo":10,"raca":"Rato-Branco"},
            {"tipo":10,"raca":"Rato-Marrom"},
            {"tipo":10,"raca":"Rato-Pequeno"},
            {"tipo":10,"raca":"Rato-de-Esgoto"},
            {"tipo":10,"raca":"Rato-de-Campo"},
            {"tipo":10,"raca":"Rato-das-Nuvens"},
            {"tipo":10,"raca":"Rato-Espinhoso"},
            {"tipo":10,"raca":"Rato-Azul"},
            {"tipo":10,"raca":"Rato-de-Grande-Orelha"},
            {"tipo":10,"raca":"Rato-de-Cauda-Longa"},
            {"tipo":10,"raca":"Rato-Preto"},
            {"tipo":10,"raca":"Rato-de-Estimação"},
            {"tipo":10,"raca":"Rato-de-Polígono"},
            {"tipo":10,"raca":"Rato-de-Areia"},
            {"tipo":10,"raca":"Rato-de-Seda"},
            {"tipo":10,"raca":"Rato-de-Bico"},
            {"tipo":10,"raca":"Rato-de-Túnel"},
            {"tipo":10,"raca":"Rato-de-Crista"},
            {"tipo":10,"raca":"Rato-de-Cauda-Peluda"},
            {"tipo":11,"raca":"Sem Raça Definida"},
            {"tipo":11,"raca":"Abyssinian"},
            {"tipo":11,"raca":"American"},
            {"tipo":11,"raca":"Peruano"},
            {"tipo":11,"raca":"Teddy"},
            {"tipo":11,"raca":"Sheltie"},
            {"tipo":11,"raca":"Texel"},
            {"tipo":11,"raca":"Coronet"},
            {"tipo":11,"raca":"Silkie"},
            {"tipo":11,"raca":"Rosetten"},
            {"tipo":11,"raca":"Angorá"},
            {"tipo":11,"raca":"Alpaca"},
            {"tipo":11,"raca":"Baldwin"},
            {"tipo":11,"raca":"Lunkarya"},
            {"tipo":11,"raca":"Merino"},
            {"tipo":11,"raca":"Rex"},
            {"tipo":11,"raca":"Satin"},
            {"tipo":11,"raca":"Teddy-Lop"},
            {"tipo":11,"raca":"White Crested"},
            {"tipo":11,"raca":"Himalaio"},
            {"tipo":12,"raca":"Sem Raça Definida"},
            {"tipo":12,"raca":"Ferret Europeu"},
            {"tipo":12,"raca":"Ferret Americano"},
            {"tipo":12,"raca":"Ferret de Patas Pretas"},
            {"tipo":12,"raca":"Ferret de Patas Brancas"},
            {"tipo":12,"raca":"Ferret Albino"},
            {"tipo":12,"raca":"Ferret Sable"},
            {"tipo":12,"raca":"Ferret Canela"},
            {"tipo":12,"raca":"Ferret Chocolate"},
            {"tipo":12,"raca":"Ferret Silver"},
            {"tipo":12,"raca":"Ferret Champagne"},
            {"tipo":12,"raca":"Ferret Padrão"},
            {"tipo":12,"raca":"Ferret Preto Sólido"},
            {"tipo":12,"raca":"Ferret Preto Sable"},
            {"tipo":12,"raca":"Ferret Preto"},
            {"tipo":12,"raca":"Ferret Blaze"},
            {"tipo":12,"raca":"Ferret Panda"},
            {"tipo":12,"raca":"Ferret Mitt"},
            {"tipo":12,"raca":"Ferret Blaze Mitt"},
            {"tipo":12,"raca":"Ferret Panda Mitt"},
            {"tipo":13,"raca":"Sem Raça Definida"},
            {"tipo":13,"raca":"Periquito-australiano"},
            {"tipo":13,"raca":"Periquito-de-colar"},
            {"tipo":13,"raca":"Periquito-de-encontro-amarelo"},
            {"tipo":13,"raca":"Periquito-rei"},
            {"tipo":13,"raca":"Periquito-de-cabeça-azul"},
            {"tipo":13,"raca":"Periquito-de-encontro-amarelo-de-pintura"},
            {"tipo":13,"raca":"Periquito-de-asa-vermelha"},
            {"tipo":13,"raca":"Periquito-arco-íris"},
            {"tipo":13,"raca":"Periquito-de-crista"},
            {"tipo":13,"raca":"Periquito-de-cauda-curta"},
            {"tipo":13,"raca":"Periquito-de-cauda-longa"},
            {"tipo":13,"raca":"Periquito-de-asa-vermelha-de-cauda-longa"},
            {"tipo":13,"raca":"Periquito-de-cauda-longa-de-encontro-amarelo"},
            {"tipo":13,"raca":"Periquito-de-asa-vermelha-de-encontro-amarelo"},
            {"tipo":13,"raca":"Periquito-de-cauda-curta-de-encontro-amarelo"},
            {"tipo":13,"raca":"Periquito-de-cauda-curta-de-crista"},
            {"tipo":13,"raca":"Periquito-de-cauda-curta-de-encontro-vermelho"},
            {"tipo":13,"raca":"Periquito-de-cauda-longa-de-encontro-vermelho"},
            {"tipo":13,"raca":"Periquito-de-encontro-vermelho"},
            {"tipo":14,"raca":"Sem Raça Definida"},
            {"tipo":14,"raca":"Gerbil-da-Mongólia"},
            {"tipo":14,"raca":"Gerbil-da-Tunísia"},
            {"tipo":14,"raca":"Gerbil-da-Califórnia"},
            {"tipo":14,"raca":"Gerbil-da-Índia"},
            {"tipo":14,"raca":"Gerbil-do-Egito"},
            {"tipo":14,"raca":"Gerbil-da-Síria"},
            {"tipo":14,"raca":"Gerbil-da-China"},
            {"tipo":14,"raca":"Gerbil-da-Argélia"},
            {"tipo":14,"raca":"Gerbil-da-Somália"},
            {"tipo":14,"raca":"Gerbil-do-Iraque"},
            {"tipo":14,"raca":"Gerbil-da-Líbia"},
            {"tipo":14,"raca":"Gerbil-do-Qatar"},
            {"tipo":14,"raca":"Gerbil-do-Kuwait"},
            {"tipo":14,"raca":"Gerbil-do-Bahrein"},
            {"tipo":14,"raca":"Gerbil-da-Arábia-Saudita"},
            {"tipo":14,"raca":"Gerbil-do-Líbano"},
            {"tipo":14,"raca":"Gerbil-da-Jordânia"},
            {"tipo":14,"raca":"Gerbil-da-Síria-Dois-Raios"},
            {"tipo":14,"raca":"Gerbil-da-Síria-Quatro-Raios"},
            {"tipo":15,"raca":"Sem Raça Definida"},
            {"tipo":15,"raca":"Iguana-verde"},
            {"tipo":15,"raca":"Iguana-do-deserto"},
            {"tipo":15,"raca":"Iguana-negra"},
            {"tipo":15,"raca":"Iguana-rinoceronte"},
            {"tipo":15,"raca":"Iguana-de-cauda-espinhosa"},
            {"tipo":15,"raca":"Iguana-das-fiji"},
            {"tipo":15,"raca":"Iguana-de-madagascar"},
            {"tipo":15,"raca":"Iguana-listrada"},
            {"tipo":15,"raca":"Iguana-vermelha"},
            {"tipo":15,"raca":"Iguana-preta"},
            {"tipo":15,"raca":"Iguana-vermelha-da-cabeça"},
            {"tipo":15,"raca":"Iguana-das-antilhas"},
            {"tipo":15,"raca":"Iguana-cauda-azul"},
            {"tipo":15,"raca":"Iguana-de-crista"},
            {"tipo":15,"raca":"Iguana-preta-das-honduras"},
            {"tipo":15,"raca":"Iguana-da-guiana"},
            {"tipo":15,"raca":"Iguana-vermelha-de-cauda-pontiaguda"},
            {"tipo":15,"raca":"Iguana-de-cauda-roxa"},
            {"tipo":15,"raca":"Iguana-dos-galápagos"},
            {"tipo":16,"raca":"Sem Raça Definida"},
            {"tipo":16,"raca":"Holandês"},
            {"tipo":16,"raca":"Netherland Dwarf"},
            {"tipo":16,"raca":"Lion Head"},
            {"tipo":16,"raca":"Mini Rex"},
            {"tipo":16,"raca":"Mini Lop"},
            {"tipo":16,"raca":"Fuzzy Lop"},
            {"tipo":16,"raca":"Dwarf Hotot"},
            {"tipo":16,"raca":"Jersey Wooly"},
            {"tipo":16,"raca":"English Angora"},
            {"tipo":16,"raca":"Holland Lop"},
            {"tipo":16,"raca":"Mini Satin"},
            {"tipo":16,"raca":"American Fuzzy Lop"},
            {"tipo":16,"raca":"Mini Plush Lop"},
            {"tipo":16,"raca":"Dwarf Papillon"},
            {"tipo":16,"raca":"Mini Lion Lop"},
            {"tipo":16,"raca":"Britannia Petite"},
            {"tipo":16,"raca":"Dwarf Cashmere Lop"},
            {"tipo":16,"raca":"Dwarf French Lop"},
            {"tipo":16,"raca":"American Sable"},
            {"tipo":17,"raca":"Sem Raça Definida"},
            {"tipo":17,"raca":"Chinchila comum"},
            {"tipo":17,"raca":"Chinchila Royal"},
            {"tipo":17,"raca":"Chinchila Degolada"},
            {"tipo":17,"raca":"Chinchila Beige"},
            {"tipo":17,"raca":"Chinchila Mosaico"},
            {"tipo":17,"raca":"Chinchila Violeta"},
            {"tipo":17,"raca":"Chinchila Ebony"},
            {"tipo":17,"raca":"Chinchila Safira"},
            {"tipo":17,"raca":"Chinchila Safira Mosaico"},
            {"tipo":17,"raca":"Chinchila Black Velvet"},
            {"tipo":17,"raca":"Chinchila Pink White"},
            {"tipo":17,"raca":"Chinchila Wilson White"},
            {"tipo":17,"raca":"Chinchila Ouro"},
            {"tipo":17,"raca":"Chinchila Diamante Preto"},
            {"tipo":17,"raca":"Chinchila Diamante Branco"},
            {"tipo":17,"raca":"Chinchila Sapphira"},
            {"tipo":17,"raca":"Chinchila Mosaic Wilson White"},
            {"tipo":17,"raca":"Chinchila Veado"},
            {"tipo":17,"raca":"Chinchila Brown Velvet"},
            {"tipo":18,"raca":"Sem Espécie Definida"},
            {"tipo":18,"raca":"Aphonopelma chalcodes"},
            {"tipo":18,"raca":"Brachypelma albopilosum"},
            {"tipo":18,"raca":"Grammostola rosea"},
            {"tipo":18,"raca":"Brachypelma smithi"},
            {"tipo":18,"raca":"Grammostola pulchripes"},
            {"tipo":18,"raca":"Brachypelma vagans"},
            {"tipo":18,"raca":"Aphonopelma seemanni"},
            {"tipo":18,"raca":"Grammostola porteri"},
            {"tipo":18,"raca":"Chromatopelma cyaneopubescens"},
            {"tipo":18,"raca":"Grammostola grossa"},
            {"tipo":18,"raca":"Thrixopelma pruriens"},
            {"tipo":18,"raca":"Grammostola pulchra"},
            {"tipo":18,"raca":"Brachypelma emilia"},
            {"tipo":18,"raca":"Pterinopelma sazimai"},
            {"tipo":18,"raca":"Lasiodora parahybana"},
            {"tipo":18,"raca":"Avicularia avicularia"},
            {"tipo":18,"raca":"Avicularia versicolor"},
            {"tipo":18,"raca":"Acanthoscurria geniculata"},
            {"tipo":18,"raca":"Brachypelma boehmei"},
            {"tipo":19,"raca":"Sem Espécie Definida"},
            {"tipo":19,"raca":"Gerbillus andersoni"},
            {"tipo":19,"raca":"Meriones libycus"},
            {"tipo":19,"raca":"Gerbillus pyramidum"},
            {"tipo":19,"raca":"Dipodillus campestris"},
            {"tipo":19,"raca":"Gerbillus gerbillus"},
            {"tipo":19,"raca":"Psammomys obesus"},
            {"tipo":19,"raca":"Gerbillus dasyurus"},
            {"tipo":19,"raca":"Meriones tristrami"},
            {"tipo":19,"raca":"Gerbillus allenbyi"},
            {"tipo":19,"raca":"Meriones sacramenti"},
            {"tipo":19,"raca":"Tatera indica"},
            {"tipo":19,"raca":"Meriones persicus"},
            {"tipo":19,"raca":"Meriones crassus"},
            {"tipo":19,"raca":"Gerbillus nanus"},
            {"tipo":19,"raca":"Meriones rex"},
            {"tipo":19,"raca":"Dipus sagitta"},
            {"tipo":19,"raca":"Gerbillus nigeriae"},
            {"tipo":19,"raca":"Meriones tamariscinus"},
            {"tipo":19,"raca":"Sekeetamys calurus"},
            {"tipo":20,"raca":"Sem Espécie Definida"},
            {"tipo":20,"raca":"Salamandra salamandra"},
            {"tipo":20,"raca":"Ambystoma mexicanum"},
            {"tipo":20,"raca":"Plethodon cinereus"},
            {"tipo":20,"raca":"Salamandrina perspicillata"},
            {"tipo":20,"raca":"Triturus cristatus"},
            {"tipo":20,"raca":"Andrias davidianus"},
            {"tipo":20,"raca":"Bolitoglossa mexicana"},
            {"tipo":20,"raca":"Triturus vulgaris"},
            {"tipo":20,"raca":"Plethodon glutinosus"},
            {"tipo":20,"raca":"Siren intermedia"},
            {"tipo":20,"raca":"Salamandra atra"},
            {"tipo":20,"raca":"Ambystoma talpoideum"},
            {"tipo":20,"raca":"Plethodon dorsalis"},
            {"tipo":20,"raca":"Salamandrina terdigitata"},
            {"tipo":20,"raca":"Triturus helveticus"},
            {"tipo":20,"raca":"Bolitoglossa conanti"},
            {"tipo":20,"raca":"Triturus marmoratus"},
            {"tipo":20,"raca":"Plethodon yonahlossee"},
            {"tipo":20,"raca":"Siren lacertina"}
        ]';

        $racas = json_decode($racas, true);

        foreach ($racas as $raca) {
            Raca::create([
                'pet_tipos_id' => $raca['tipo'],
                'raca' => $raca['raca']
            ]);
        }
    }
}